### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Viketk** [Viketk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by testvike** [comment]
Вікто́рія (англ. Victoria, ім'я при хрещенні Александріна Вікто́рія — англ. Alexandrina Victoria; 24 травня 1819 — 22 січня 1901) — королева Великої Британії з 1837 року.
Власноручно розробляє правила етикету і править країною.
