### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Viketk** [Viketk/homepage#6]
20 червня 1837 року - коронація 18-літньої королеви, по закінченні якої негайно попросила чашку чаю і свіжий номер «Таймс».
Лютий 1840 року - одруження королеви з Альбертом, князем Кобурзьким.
Британія уникає антимонархічні потрясіння які охоплюють Європу в 1848 році, завдяки високому моральному престижу королівської родини
1846 рік - подарунок яхти «Вікторія» для Санкт-Петербурзького Імператорського яхт-клубу.

**Comment by testvike** [comment]
20 червня 1837 року - коронація 18-літньої королеви, по закінченні якої негайно попросила чашку чаю і свіжий номер «Таймс».
Лютий 1840 року - одруження королеви з Альбертом, князем Кобурзьким.
Британія уникає антимонархічні потрясіння які охоплюють Європу в 1848 році, завдяки високому моральному престижу королівської родини
1846 рік - подарунок яхти «Вікторія» для Санкт-Петербурзького Імператорського яхт-клубу
